proteinevolution/Toolkit

app/assets/ui/app/helper.ts, app/assets/ui/app/paramvalidation.ts, app/assets/ui/app/sampleseq.ts, app/assets/ui/app/validation.ts
=> validate samcc helices on paste

modules/auth/src/main/scala/de/proteinevolution/auth/models/MailTemplate.scala, public/mail_example.mjml
In the future, we should also take a look at simplifying this by using a local version of mjml.
closes #440
=> Mails styled

modules/results/src/main/scala/de/proteinevolution/results/models/resultviews/ModellerResultView.scala, tel/runscripts/modeller.sh
Also, removed SOVX and ANOLEA are they are error-prone;
should be replaced with more actual methods.
=> Models have the correct start wrt the query

app/services/Configuration.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/services/JobDispatcher.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/services/JobIdProvider.scala
* remove superfluous loc
* only use lifecycle hook in production
=> small refactorings:

conf/application.conf
=> add missing configuration fields

project/Dependencies.scala
This reverts commit d6ef52097ca453fd5ac5fbc50ae170ccfb241885.
=> Revert "akka 2.5.18 (#740)"

modules/common/src/main/scala/de/proteinevolution/models/param/ParamType.scala
Fixed Gauss min and max brackets as variable names, added minimum and maximum constraints for the validation.
=> Character fix in validation

app/assets/ui/app/jobview/input.ts, app/assets/ui/app/jobview/submission.ts, modules/common/src/main/scala/de/proteinevolution/models/ConstantsV2.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/controllers/SubmissionController.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/services/JobDispatcher.scala
further issues: the mpfd is dynamically used as a container for params
we should validate them properly and type them, issue #705
=> closes #760: only allow single file upload with content type text/plain

conf/tools.conf
The latest version of Uniclust30 is quite vast.
=> Increased memory available for some tools

conf/application.conf
which should not rely on overriding config files to exist
=> hostname should have a meaningful value

modules/backend/src/main/scala/de/proteinevolution/backend/controllers/BackendController.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/actors/JobActor.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/dao/JobDao.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/services/JobHashService.scala, modules/results/src/main/scala/de/proteinevolution/results/services/ResultGetService.scala, modules/results/src/main/scala/de/proteinevolution/results/services/ToolNameGetService.scala, modules/search/src/main/scala/de/proteinevolution/search/services/SearchService.scala
leaving other daos as is because of ongoing changes in other branches
=> issue #824: refactor jobDao

project/Dependencies.scala
We should consider uploading our local dependencies on bintray or similar services.
=> use geoip version 1.5.7 (new sbt)

build.sbt, modules/auth/src/main/scala/de/proteinevolution/auth/UserSessions.scala, modules/auth/src/main/scala/de/proteinevolution/auth/controllers/AuthController.scala, modules/auth/src/main/scala/de/proteinevolution/auth/controllers/ValidationController.scala, modules/auth/src/main/scala/de/proteinevolution/auth/dao/UserDao.scala, modules/auth/src/main/scala/de/proteinevolution/auth/models/FormDefinitions.scala, modules/auth/src/main/scala/de/proteinevolution/auth/models/JSONTemplate.scala, modules/auth/src/main/scala/de/proteinevolution/auth/models/MailTemplate.scala, modules/backend/src/main/scala/de/proteinevolution/backend/actors/DatabaseMonitor.scala, modules/backend/src/main/scala/de/proteinevolution/backend/controllers/BackendController.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/actors/JobActor.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/services/JobDispatcher.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/services/JobIdProvider.scala, modules/search/src/main/scala/de/proteinevolution/search/services/SearchService.scala, modules/user/src/main/scala/de/proteinevolution/user/IPConfig.scala, modules/user/src/main/scala/de/proteinevolution/user/Location.scala, modules/user/src/main/scala/de/proteinevolution/user/SessionData.scala, modules/user/src/main/scala/de/proteinevolution/user/User.scala, modules/user/src/main/scala/de/proteinevolution/user/UserConfig.scala, modules/user/src/main/scala/de/proteinevolution/user/UserData.scala, modules/user/src/main/scala/de/proteinevolution/user/UserToken.scala, modules/util/src/main/scala/de/proteinevolution/util/LocationProvider.scala, modules/verification/src/main/scala/de/proteinevolution/verification/controllers/VerificationController.scala
waited for this because of #708 but prepone it now.
=> decouple user models because they don't belong in common

modules/cluster-api/src/main/scala/de/proteinevolution/cluster/api/SGELoad.scala, modules/cluster/src/main/scala/de/proteinevolution/cluster/ClusterSubscriber.scala, modules/message/src/main/scala/de/proteinevolution/message/actors/WebSocketActor.scala
we need to ask the current load at prestart of any new websocket connection
=> since we don't do polling for the load anymore but are message-driven

conf/tools.conf
Updated HHsuite to v3.2.0. It contains binaries and scripts for HHpred and HHblits.
=> Closes #878

project/Dependencies.scala
this adds support for BSONObjectIDs
=> upgrade circe bson

app/assets/ui/app/jobview/submission.ts
IE does not support fileInput.remove() and fileInput.remove()
methods and consequently, job submisson was broken.
=> Submission of jobs on IE was broken.

project/Dependencies.scala
last working version in prod was 0.16.2
=> reactivemongo 0.17

app/assets/ui/app/validation.ts, conf/tools.conf, modules/results/src/main/scala/de/proteinevolution/results/results/Common.scala, modules/results/src/main/scala/de/proteinevolution/results/results/Quick2DResult.scala, modules/results/src/main/twirl/views/resultpanels/quick2d.scala.html, tel/env/environment.sh, tel/paramspec/quick_iters.prop, tel/runscripts/quick2d.sh
Included NetSurfP2 for secondary structure and disorder prediction.
Updated SPIDER2 to SPIDER3, PSSpred3 to PSSpred4, and SignalP4.0 to
SignalP5.0.
=> Updated Quick2D

modules/backend/src/main/scala/de/proteinevolution/backend/actors/DatabaseMonitor.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/controllers/JobGetController.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/services/JobResubmitService.scala, modules/results/src/main/scala/de/proteinevolution/results/services/ResultGetService.scala
the project did not compile and the tests failed,
why was this merged into develop?
=> fix unused imports

modules/auth/src/main/scala/de/proteinevolution/auth/UserSessions.scala, modules/auth/src/main/scala/de/proteinevolution/auth/controllers/AuthController.scala, modules/auth/src/main/scala/de/proteinevolution/auth/controllers/ValidationController.scala, modules/auth/src/main/scala/de/proteinevolution/auth/models/FormDefinitions.scala, modules/backend/src/main/scala/de/proteinevolution/backend/actors/DatabaseMonitor.scala, modules/backend/src/main/scala/de/proteinevolution/backend/controllers/BackendController.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/dao/JobDao.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/models/Job.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/models/JobClusterData.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/services/JobHasher.scala, modules/migrations/src/main/java/de/proteinevolution/migrations/changelogs/DatabaseChangelog.java, modules/user/src/main/scala/de/proteinevolution/user/User.scala, modules/user/src/main/scala/de/proteinevolution/user/UserData.scala, modules/verification/src/main/scala/de/proteinevolution/verification/controllers/VerificationController.scala
Next up we should use BSON macro handlers.
=> Use Camel Case in MongoDB

frontend/package.json, frontend/public/index.html, frontend/src/components/index/ToolFinder.vue, frontend/src/components/navigation/Footer.vue, frontend/src/components/navigation/NavBar.vue, frontend/src/main.ts, frontend/yarn.lock
I will try to fix incompatibilities for IE and Edge.
=> IE & Edge Fixes

frontend/src/assets/scss/_form-elements.scss, frontend/src/assets/scss/_variables.scss, frontend/src/components/tools/ToolView.vue, frontend/src/components/tools/parameters/BooleanParameter.vue, frontend/src/components/tools/parameters/NumberParameter.vue, frontend/src/components/tools/parameters/Section.vue, frontend/src/components/tools/parameters/SelectParameter.vue, frontend/src/components/tools/parameters/TextInputParameter.vue, frontend/src/components/tools/parameters/special/HHpredSelectsParameter.vue, frontend/src/i18n/lang/modules/jobs-en.ts, frontend/src/mixins/ParameterRememberMixin.ts, frontend/src/types/toolkit/tools.ts, modules/tools/src/main/scala/de/proteinevolution/tools/parameters/ParamAccess.scala, modules/tools/src/main/scala/de/proteinevolution/tools/parameters/Parameter.scala
=> Params fix

conf/tools.conf, frontend/src/i18n/lang/modules/tools-en.ts, frontend/src/types/toolkit/tools.ts, frontend/src/util/validation.ts, modules/tools/src/main/scala/de/proteinevolution/tools/ToolConfig.scala, modules/tools/src/main/scala/de/proteinevolution/tools/forms/ToolFormSimple.scala, modules/tools/src/main/scala/de/proteinevolution/tools/forms/ValidationParamsForm.scala, modules/ui/src/main/scala/de/proteinevolution/ui/controllers/UiController.scala
Cleans up the validation params provided by the backend (should
be specific to the input type)
=> Create validation params depending on input type

.gitignore, frontend/package.json, frontend/src/components/jobmanager/JobManagerView.vue, frontend/src/components/jobs/result-tabs/sections/HitListTable.vue, frontend/src/components/tools/ToolView.vue, frontend/yarn.lock
=> Fix frontend dependencies

build.sbt
=> update kind projector

build.sbt, conf/application.conf, conf/logback.xml, modules/backend/src/main/scala/de/proteinevolution/backend/controllers/BackendController.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/controllers/JobGetController.scala, modules/jobs/src/main/scala/de/proteinevolution/jobs/models/Job.scala, modules/tel/src/main/scala/de/proteinevolution/tel/param/ParamCollector.scala, modules/tools/src/main/scala/de/proteinevolution/tools/ConfigWatcher.scala, modules/tools/src/main/scala/de/proteinevolution/tools/ToolConfig.scala, modules/tools/src/main/scala/de/proteinevolution/tools/ToolsModule.scala, modules/ui/src/main/scala/de/proteinevolution/ui/controllers/UiController.scala, project/Dependencies.scala, project/Settings.scala
- remove usage of `var`
- initialize file watcher in module binding eagerly
- use more functional syntax
=> refactor file watcher

.github/workflows/frontend.yml
yesterday ubuntu-latest was updated and
node was upgraded to 16:
https://github.com/actions/virtual-environments/commit/d0f20ddfa317289a4875d0c6916b285e8ebf8ca3
This caused a build error in our pipeline
=> frontend build failed because it used node 16
